---
- hosts: all
  tasks:
  - name: Create user
    user:
      name: "{{ USER }}"
      password: "{{ 'PASSWORD' | password_hash('sha512') }}"
      shell: /bin/nologin
      update_password: on_create



