---
- hosts: notificaciones
  tasks:
  - name: Get user
    getent:
      database: passwd
      key: jnk_var_user

  - name: Validate user
    fail:
      msg: Eser already exist
    when: getent_password is not defined 
    
  - name: Create user
    user:
      name: jnk_var_user
      password: "{{ 'jnk_var_password' | password_hash('sha512') }}"
      shell: /bin/nologin
      update_password: on_create



