---
- hosts: notificaciones
  tasks:
  - name: Get user
    getent:
      database: passwd
      
  - name: Show gathered local user names only
    debug:
      msg: "{{ item }}"
    loop: "{{ getent_passwd.keys() | list }}"
    when: ansible_check_mode

  - name: Create user
    user:
      name: jnk_var_user
      password: "{{ 'jnk_var_password' | password_hash('sha512') }}"
      shell: /bin/nologin
      update_password: on_create



