---
- hosts: notificaciones
  tasks:
  - name: Get user
    getent:
      database: passwd
      key: jnk_var_user

 - name: Show gathered local user names only
    debug:
      msg: "getent_passwd"
    when: ansible_check_mode

  - name: Create user
    user:
      name: jnk_var_user
      password: "{{ 'jnk_var_password' | password_hash('sha512') }}"
      shell: /bin/nologin
      update_password: on_create



