---
- hosts: notificaciones
  tasks:
  - name: Get user
    getent:
      database: passwd
      
  - name: Show gathered local user names only
    debug:
      msg: "{{ item }}"
    loop: "{{ getent_passwd.keys() | list }}"
    when: ansible_check_mode

  - name: Check if local user account jnk_var_user exists
    assert:
      that:
        - jnk_var_user not in getent_passwd.keys()
      fail_msg: "Given user exists!"
      success_msg: "Given no  exists."

  - name: Create user
    user:
      name: jnk_var_user
      password: "{{ 'jnk_var_password' | password_hash('sha512') }}"
      shell: /bin/nologin
      update_password: on_create



